version: '3.9'

services:
  rails:
    image: performance/rails
    ports:
      - 3000:3000
    volumes:
      - ./rails:/myapp
  sinatra:
    image: performance/sinatra
    ports:
      - 3001:4567
    volumes:
      - ./sinatra:/myapp
    command: bundle exec rackup --host 0.0.0.0 -p 4567
  express:
    image: performance/express
    ports:
      - 3002:3002
    volumes:
      - ./express:/myapp
    command: node index.js
  flask:
    image: performance/flask
    ports:
      - 3003:5000
    environment:
      - FLASK_APP=myapp
    volumes:
      - ./flask:/myapp
  django:
    image: performance/django
    ports:
      - 3004:8000
    volumes:
      - ./django:/myapp
  laravel:
    image: performance/laravel
    ports:
      - 3005:8181
    volumes:
      - ./laravel:/myapp
